baseURL: https://leonardoportfolio.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Click on the tabs below to learn more about who I am!
    title: Hi, my name is Leonardo Riolo
  blog: {}
  contact:
    address:
      - city: London  
        country: United Kingdom
        street: Regent's Park
        title: NW14SA 
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lriolo.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (39) 3483987382
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/leonardo_riolo
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/leonardo.riolo.1
      #- icon: fa-instagram
      #  label: Instagram
      #  url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Leonardo9797
     # - icon: fa-linkedin
    #    label: LinkedIn
     #   url: https://www.linkedin.com/in/leonardoriolo/
  image: ''
  name: Leonardo Riolo
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: A sailor passionate about business
        title: My story
        url: blogs/my_story
        
      - image: programming.jpg
        subtitle: The first steps
        title: Learning R 
        url: blogs/beginnings_R
        
      - image: Argentina.jpg
        subtitle: From India to Argentina
        title: My travels
        url: blogs/travelling
        
      #- image: pic04.jpg
       # subtitle: Nisl Sed Aliquam
        #title: Ipsum
        #url: blogs/ipsum
      
     
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Having the basics - a good bed to sleep in, good relationships, good food, and good sex - is most important, and those things don’t get much better when you have a lot of money or much worse when you have less. And the people one meets at the top aren’t necessarily more special than those one meets at the bottom or in between. Ray Dalio"
    title: Markets as a Passion
    url: blogs
